Repository team-eungae/eungae-pediatric_appointment, pull requests merged in 2023-12, with the labels that each got.

#17 [FE] Feat: 병원 상세 페이지 프론트 작성
  src/main/resources/static/css/hospital-details.css
  src/main/resources/static/js/hospital-details.js
  src/main/resources/templates/find-hospital.html
  src/main/resources/templates/hospital-details.html
Labels: 🎨 프론트엔드

#28 Revert "[FE] Feat: 커뮤니티 글목록 페이지 작업"
  src/main/resources/static/css/community.css
  src/main/resources/static/css/medical-records.css
  src/main/resources/static/js/medical-records.js
  src/main/resources/templates/community.html
  src/main/resources/templates/medical-records.html
Labels: 🛠️ 리팩토링, 🎨 프론트엔드

#33 [FE] Feat: 커뮤니티 글목록 페이지 작업
  src/main/resources/static/css/community-list.css
  src/main/resources/templates/community-list.html
Labels: 🎨 프론트엔드

#41 [FE] Feat: 커뮤니티 글쓰기 페이지 작업
  src/main/resources/static/css/community-write.css
  src/main/resources/templates/community-write.html
Labels: 🎨 프론트엔드

#42 [FE] Feat: 주변 병원 찾기 프론트
  src/main/java/com/playdata/eungae/HomeController.java
  src/main/resources/static/css/map.css
  src/main/resources/static/img/basic4.png
  src/main/resources/static/img/eungaemarker.png
  src/main/resources/static/js/map.js
  src/main/resources/templates/map.html
Labels: 🛠️ 리팩토링, 🎨 프론트엔드

#43 [FE] Feat: 마이페이지 개발하기
  src/main/resources/static/css/my-page.css
  src/main/resources/templates/my-page.html
Labels: 🎨 프론트엔드

#48 [FE] Feat: 예약 페이지 프론트
  src/main/resources/static/css/appointment.css
  src/main/resources/static/img/doctor.jpeg
  src/main/resources/static/js/appointment.js
  src/main/resources/templates/appointment.html
Labels: 🎨 프론트엔드

#46 [FE] Feat: 커뮤니티 게시글 상세보기 페이지 작업
  src/main/resources/static/css/community-post-details.css
  src/main/resources/templates/community-post-details.html
Labels: 🎨 프론트엔드

#50 [FE] Feat: 내 예약 확인 페이지 작업
  src/main/resources/static/css/medical-records.css
  src/main/resources/static/js/medical-records.js
  src/main/resources/templates/medical-records.html
Labels: 🎨 프론트엔드

#51 [FE] Feat: 진료내역 확인 페이지 작업
  src/main/resources/static/css/my-reservations.css
  src/main/resources/templates/my-reservations.html
Labels: 🎨 프론트엔드

#52 [FE] Fix: 마이페이지 css 경로 수정
  src/main/resources/templates/my-page.html
Labels: 🚨 버그, 🛠️ 리팩토링, 🎨 프론트엔드

#54 [FE] Fix: 마이페이지 css 경로 수정
  src/main/resources/templates/my-page.html
Labels: 🚨 버그, 🎨 프론트엔드

#57 [ALL] Chore: application.properties 확장자 yaml로 변경
  src/main/resources/application.yml
Labels: ⚙️ 환경설정

#70 [BE] Feat: 패키지 구조 설계 작업
  src/main/java/com/playdata/eungae/appointment/application/dummy.txt
  src/main/java/com/playdata/eungae/appointment/domain/repository/dummy.txt
  src/main/java/com/playdata/eungae/appointment/dto/dummy.txt
  src/main/java/com/playdata/eungae/appointment/exception/dummy.txt
  src/main/java/com/playdata/eungae/appointment/presentation/AppointmentViewController.java
  src/main/java/com/playdata/eungae/community/application/dummy.txt
  src/main/java/com/playdata/eungae/community/domain/repository/dummy.txt
  src/main/java/com/playdata/eungae/community/dto/dummy.txt
  src/main/java/com/playdata/eungae/community/exception/dummy.txt
  src/main/java/com/playdata/eungae/community/presentation/CommunityViewController.java
  src/main/java/com/playdata/eungae/hospital/application/dummy.txt
  src/main/java/com/playdata/eungae/hospital/domain/repository/dummy.txt
  src/main/java/com/playdata/eungae/hospital/dto/dummy.txt
  src/main/java/com/playdata/eungae/hospital/exception/dummy.txt
  src/main/java/com/playdata/eungae/hospital/presentation/HospitalViewController.java
  src/main/java/com/playdata/eungae/member/application/dummy.txt
  src/main/java/com/playdata/eungae/member/domain/repository/dummy.txt
  src/main/java/com/playdata/eungae/member/dto/dummy.txt
  src/main/java/com/playdata/eungae/member/exception/dummy.txt
  src/main/java/com/playdata/eungae/member/presentation/MemberViewController.java
Labels: 💻 백엔드

#74 [BE] Feat : Hospital entity 추가
  src/main/java/com/playdata/eungae/hospital/domain/Hospital.java
Labels: 💻 백엔드

#75 [BE] Feat : Doctor entity 추가
  src/main/java/com/playdata/eungae/hospital/domain/Doctor.java
Labels: 💻 백엔드

#77 [BE] Feat: Member Entity 개발
  src/main/java/com/playdata/eungae/member/domain/Member.java
Labels: 💻 백엔드

#80 [BE] Feat: Base Entity 작성
  src/main/java/com/playdata/eungae/EungaeApplication.java
  src/main/java/com/playdata/eungae/base/BaseEntity.java
  src/main/java/com/playdata/eungae/doctor/application/dummy.txt
  src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
  src/main/java/com/playdata/eungae/doctor/dto/dummy.txt
  src/main/java/com/playdata/eungae/doctor/exception/dummy.txt
Labels: 💻 백엔드

#83 [BE] Feat: Review Entity 생성
  src/main/java/com/playdata/eungae/review/application/dummy.txt
  src/main/java/com/playdata/eungae/review/domain/Review.java
  src/main/java/com/playdata/eungae/review/domain/repository/dummy.txt
  src/main/java/com/playdata/eungae/review/dto/dummy.txt
  src/main/java/com/playdata/eungae/review/exception/dummy.txt
  src/main/java/com/playdata/eungae/review/presentation/ReviewViewController.java
Labels: 💻 백엔드

#88 [BE] Feat: Children Entity 완료
  src/main/java/com/playdata/eungae/member/domain/Children.java
Labels: 💻 백엔드

#89 [BE] Feat: hospital_schedule 엔티티 생성
  src/main/java/com/playdata/eungae/hospital/domain/HospitalSchedule.java
Labels: 💻 백엔드

#93 [BE] Feat: Appointment 엔티티를 완료하였습니다.
  src/main/java/com/playdata/eungae/appointment/domain/repository/Appointment.java
Labels: 💻 백엔드

#97 [BE] Fix: HospitalImage Entity 파일 위치 변경
  src/main/java/com/playdata/eungae/hospital/domain/HospitalImage.java
Labels: 💻 백엔드

#99 [ALL] Docs: ERD, 기능명세서, endpoint 명세서 첨부
  build.gradle
  src/main/resources/static/document/응애-소아과 예약-ERD.svg
  src/main/resources/static/document/응애_기능명세서_endpoint.pdf
Labels: 📃 문서

#103 [BE] Feat: @Controller로 기능 화면 연결
  src/main/java/com/playdata/eungae/HomeController.java
  src/main/java/com/playdata/eungae/appointment/presentation/AppointmentViewController.java
  src/main/java/com/playdata/eungae/article/application/dummy.txt
  src/main/java/com/playdata/eungae/article/domain/repository/dummy.txt
  src/main/java/com/playdata/eungae/article/dto/dummy.txt
  src/main/java/com/playdata/eungae/article/exception/dummy.txt
  src/main/java/com/playdata/eungae/article/presentation/ArticleViewController.java
  src/main/java/com/playdata/eungae/community/presentation/CommunityViewController.java
  src/main/java/com/playdata/eungae/hospital/presentation/HospitalViewController.java
  src/main/java/com/playdata/eungae/member/presentation/MemberViewController.java
Labels: 💻 백엔드

#105 [BE] Fix: Entity 패키지 수정 및 dummy.txt 파일 삭제
  src/main/java/com/playdata/eungae/appointment/application/dummy.txt
  src/main/java/com/playdata/eungae/appointment/domain/Appointment.java
  src/main/java/com/playdata/eungae/appointment/domain/repository/dummy.txt
  src/main/java/com/playdata/eungae/appointment/dto/dummy.txt
  src/main/java/com/playdata/eungae/appointment/exception/dummy.txt
  src/main/java/com/playdata/eungae/article/application/dummy.txt
  src/main/java/com/playdata/eungae/article/domain/CommunityBoard.java
  src/main/java/com/playdata/eungae/article/domain/repository/dummy.txt
  src/main/java/com/playdata/eungae/article/dto/dummy.txt
  src/main/java/com/playdata/eungae/article/exception/dummy.txt
  src/main/java/com/playdata/eungae/doctor/application/dummy.txt
  src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
  src/main/java/com/playdata/eungae/doctor/domain/DoctorClosed.java
  src/main/java/com/playdata/eungae/doctor/domain/repository/dummy.txt
  src/main/java/com/playdata/eungae/doctor/dto/dummy.txt
  src/main/java/com/playdata/eungae/doctor/exception/dummy.txt
  src/main/java/com/playdata/eungae/hospital/application/dummy.txt
  src/main/java/com/playdata/eungae/hospital/domain/repository/dummy.txt
  src/main/java/com/playdata/eungae/hospital/dto/dummy.txt
  src/main/java/com/playdata/eungae/hospital/exception/dummy.txt
  src/main/java/com/playdata/eungae/member/application/dummy.txt
  src/main/java/com/playdata/eungae/member/domain/repository/dummy.txt
  src/main/java/com/playdata/eungae/member/dto/dummy.txt
  src/main/java/com/playdata/eungae/member/exception/dummy.txt
  src/main/java/com/playdata/eungae/review/application/dummy.txt
  src/main/java/com/playdata/eungae/review/domain/repository/dummy.txt
  src/main/java/com/playdata/eungae/review/dto/dummy.txt
  src/main/java/com/playdata/eungae/review/exception/dummy.txt
Labels: 💻 백엔드, 🚨 버그

#107 [ALL] Docs: README.md 수정
  README.md
Labels: 📃 문서

#110 [BE] Chore: application.yml, build.gradle 수정하여 DB 접근 로직 생성
  build.gradle
  src/main/resources/application.yml
Labels: 💻 백엔드

#111 [BE] Feat: Entity들의 연관관계를 설정하고 불필요한 import문을 정리했습니다.
  src/main/java/com/playdata/eungae/appointment/domain/Appointment.java
  src/main/java/com/playdata/eungae/appointment/domain/AppointmentDocument.java
  src/main/java/com/playdata/eungae/appointment/presentation/AppointmentViewController.java
  src/main/java/com/playdata/eungae/article/domain/CommunityBoard.java
  src/main/java/com/playdata/eungae/article/presentation/ArticleViewController.java
  src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
  src/main/java/com/playdata/eungae/doctor/domain/DoctorClosed.java
  src/main/java/com/playdata/eungae/doctor/domain/DoctorSchedule.java
  src/main/java/com/playdata/eungae/hospital/domain/Hospital.java
  src/main/java/com/playdata/eungae/hospital/domain/HospitalImage.java
  src/main/java/com/playdata/eungae/hospital/domain/HospitalSchedule.java
  src/main/java/com/playdata/eungae/member/domain/Children.java
  src/main/java/com/playdata/eungae/member/domain/Member.java
  src/main/java/com/playdata/eungae/review/domain/Review.java
Labels: 💻 백엔드

#113 [FE] Feat: 자녀 관리 페이지 작업
  src/main/java/com/playdata/eungae/member/presentation/MemberViewController.java
  src/main/resources/static/css/my-children-add.css
  src/main/resources/static/css/my-children.css
  src/main/resources/static/img/default-children-2.png
  src/main/resources/static/js/my-children-add.js
  src/main/resources/templates/contents/member/my-children-add.html
  src/main/resources/templates/contents/member/my-children.html
  src/main/resources/templates/contents/member/my-page.html
Labels: 🎨 프론트엔드

#115 [BE] Fix: DoctorClosed 엔티티 변수명 수정
  src/main/java/com/playdata/eungae/doctor/domain/DoctorClosed.java
Labels: 💻 백엔드, 🚨 버그

#116 [FE] Feat: 회원가입 비밀번호 유효성 검사 구현
  src/main/resources/static/css/sign-up.css
  src/main/resources/static/js/sign-up.js
  src/main/resources/templates/contents/member/sign-up.html
Labels: 🎨 프론트엔드

#126 [BE] Fix: DoctorClosed 엔티티 컬럼명 수정
  src/main/java/com/playdata/eungae/doctor/domain/DoctorClosed.java
Labels: 💻 백엔드

#124 [BE] Feat: HospitalClosed 엔티티 작성
  src/main/java/com/playdata/eungae/hospital/domain/HospitalClosed.java
Labels: 💻 백엔드

#129 [FE] Feat: 로그인 페이지 개발
  src/main/java/com/playdata/eungae/HomeController.java
  src/main/resources/static/css/login.css
  src/main/resources/templates/contents/member/login.html
Labels: 🎨 프론트엔드

#132 [ALL] Feat: 내 진료기록 열람 페이지 생성 및 컨트롤러 매핑
  src/main/java/com/playdata/eungae/member/presentation/MemberViewController.java
  src/main/resources/static/css/medical-records-details.css
  src/main/resources/static/js/medical-records.js
  src/main/resources/templates/contents/member/medical-records-details.html
  src/main/resources/templates/contents/member/medical-records.html
Labels: 💻 백엔드, 🎨 프론트엔드

#130 [ALL] Feat: 병원 상세 리뷰 목록 구현 및 컨트롤러 매핑
  src/main/resources/static/css/hospital-details.css
  src/main/resources/static/css/my-review.css
  src/main/resources/templates/contents/hospital/hospital-details.html
  src/main/resources/templates/contents/member/my-review.html
  src/main/resources/templates/fragments/hospitalBottomNavbar.html
  src/main/resources/templates/layouts/hospital_layout.html
Labels: 💻 백엔드, 🎨 프론트엔드

#133 [ALL] Chore: .gitignore 수정
  .gitignore
Labels: ⚙️ 환경설정

#134 [BE] Fix: 엔티티 수정
  src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
  src/main/java/com/playdata/eungae/hospital/domain/Hospital.java
  src/main/java/com/playdata/eungae/hospital/domain/HospitalImage.java
Labels: 💻 백엔드, 🚨 버그

#135 [ALL] Feat: 내 정보 수정 페이지 화면 개발 및 컨트롤러 매핑
  src/main/resources/static/css/my-page-form.css
  src/main/resources/static/js/my-page-form.js
  src/main/resources/templates/contents/member/my-page-form.html
Labels: 🎨 프론트엔드

#136 [ALL] Feat: 내 정보 수정 페이지 화면 개발 및 컨트롤러 매핑
  src/main/java/com/playdata/eungae/member/presentation/MemberViewController.java
  src/main/resources/templates/contents/member/my-page-form.html
  src/main/resources/templates/contents/member/my-page.html
Labels: 💻 백엔드, 🎨 프론트엔드

#137 [ALL] Feat: 회원 탈퇴하기 페이지 및 컨트롤러 매핑
  src/main/resources/static/css/my-page.css
  src/main/resources/static/js/my-page.js
  src/main/resources/templates/contents/member/my-page.html
Labels: 🎨 프론트엔드

#139 [ALL] Feat: 회원 탈퇴하기 페이지 및 컨트롤러 매핑
  src/main/resources/static/css/my-page.css
Labels: 🎨 프론트엔드

#141 [BE] Feat : Entity 연관관계 FetchType 설정
  src/main/java/com/playdata/eungae/appointment/domain/Appointment.java
  src/main/java/com/playdata/eungae/appointment/domain/AppointmentDocument.java
  src/main/java/com/playdata/eungae/article/domain/CommunityBoard.java
  src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
  src/main/java/com/playdata/eungae/doctor/domain/DoctorSchedule.java
  src/main/java/com/playdata/eungae/hospital/domain/Hospital.java
  src/main/java/com/playdata/eungae/hospital/domain/HospitalImage.java
  src/main/java/com/playdata/eungae/hospital/domain/HospitalSchedule.java
  src/main/java/com/playdata/eungae/review/domain/Review.java
Labels: 💻 백엔드

#144 [BE] Feat: 패키지 구조를 레이어드 아키텍쳐 방식으로 바꾸기
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java
  src/main/java/com/playdata/eungae/doctor/controller/DoctorViewController.java
  src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/review/controller/ReviewViewController.java
Labels: 💻 백엔드, 🛠️ 리팩토링
