Repository team-eungae/eungae-pediatric_appointment, pull requests merged in 2024-01, with the labels that each got.

#150 [BE] Fix : Entity 내부 스펙 변경
  src/main/java/com/playdata/eungae/appointment/domain/Appointment.java
  src/main/java/com/playdata/eungae/hospital/domain/Hospital.java
  src/main/java/com/playdata/eungae/review/controller/ReviewApiController.java
  src/main/java/com/playdata/eungae/review/domain/Review.java
  src/main/java/com/playdata/eungae/review/dto/RequestReviewFormDto.java
  src/main/java/com/playdata/eungae/review/repository/ReviewRepository.java
  src/main/java/com/playdata/eungae/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/playdata/eungae/review/service/ReviewService.java
  src/main/java/com/playdata/eungae/review/service/ReviewServiceImpl.java
Labels: 💻 백엔드, 🛠️ 리팩토링

#152 [BE] Feat : Test 더미데이터를 추가하기 위한 PostConstruct 추가
  src/main/java/com/playdata/eungae/initDB.java
Labels: 💻 백엔드

#148 [BE] Fix: 멤버 테이블 카카오로그인 구분 컬럼 추가 및 아이디 컬럼명 변경
  src/main/java/com/playdata/eungae/member/domain/Member.java
Labels: 💻 백엔드, 🛠️ 리팩토링

#158 [BE] Feat: 자체 회원가입 기능 스케치 개발
  src/main/java/com/playdata/eungae/member/controller/MemberApiController.java
  src/main/java/com/playdata/eungae/member/domain/Member.java
  src/main/java/com/playdata/eungae/member/dto/SignUpMemberRequestDto.java
  src/main/java/com/playdata/eungae/member/repository/MemberRepository.java
  src/main/java/com/playdata/eungae/member/service/MemberService.java
Labels: 💻 백엔드

#160 [BE] Feat: Spring Security 추가 및 Config 설정
  .gitignore
  src/main/java/com/playdata/eungae/config/WebSecurityConfig.java
Labels: 💻 백엔드

#166 [BE] Feat: 자체 회원가입 개발
  src/main/java/com/playdata/eungae/config/WebSecurityConfig.java
  src/main/java/com/playdata/eungae/member/controller/MemberApiController.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/domain/Member.java
  src/main/java/com/playdata/eungae/member/dto/SignUpMemberRequestDto.java
  src/main/java/com/playdata/eungae/member/repository/MemberRepository.java
  src/main/java/com/playdata/eungae/member/service/MemberService.java
  src/test/java/com/playdata/eungae/member/service/MemberServiceTest.java
  src/test/java/com/playdata/eungae/review/service/ReviewServiceTest.java
Labels: 💻 백엔드, 📝 테스트

#173 [BE] Feat: 자녀관리 기능 개발
  build.gradle
  src/main/java/com/playdata/eungae/member/controller/ChildrenController.java
  src/main/java/com/playdata/eungae/member/domain/Children.java
  src/main/java/com/playdata/eungae/member/dto/ChildrenDto.java
  src/main/java/com/playdata/eungae/member/repository/ChildrenRepository.java
  src/main/java/com/playdata/eungae/member/service/ChildrenService.java
  src/main/resources/static/js/my-children-add.js
  src/main/resources/templates/contents/member/my-children-add.html
  src/main/resources/templates/contents/member/my-children.html
Labels: 💻 백엔드

#177 [BE] Fix: Appointment 엔티티
  src/main/java/com/playdata/eungae/appointment/domain/Appointment.java
Labels: 💻 백엔드

#178 [BE] Feat: 마이페이지 구현
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/domain/Member.java
  src/main/java/com/playdata/eungae/member/dto/MemberFindResponseDto.java
  src/main/java/com/playdata/eungae/member/dto/MemberUpdateRequestDto.java
  src/main/java/com/playdata/eungae/member/dto/MemberUpdateResponseDto.java
  src/main/java/com/playdata/eungae/member/service/MemberService.java
  src/main/resources/templates/contents/member/my-page.html
Labels: 💻 백엔드

#180 [BE] Fix: PR 후 오류 수정
  build.gradle
  src/main/java/com/playdata/eungae/config/WebSecurityConfig.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/domain/Children.java
  src/main/java/com/playdata/eungae/member/repository/MemberRepository.java
  src/main/java/com/playdata/eungae/member/service/MemberService.java
Labels: 💻 백엔드, 🚨 버그, ⚙️ 환경설정

#165 [BE] Feat: 병원, 병원 스케줄 생성 기능 구현
  src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java
  src/main/java/com/playdata/eungae/hospital/domain/Hospital.java
  src/main/java/com/playdata/eungae/hospital/domain/HospitalSchedule.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalRegisterRequestDto.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalScheduleRequestDto.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalScheduleViewResponseDto.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalViewResponseDto.java
  src/main/java/com/playdata/eungae/hospital/repository/HospitalRepository.java
  src/main/java/com/playdata/eungae/hospital/repository/HospitalScheduleRepository.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
  src/test/java/com/playdata/eungae/hospital/service/HospitalServiceImplTest.java
Labels: 💻 백엔드

#181 [BE] Feat : 즐겨찾기 추가, 삭제 기능 구현
  src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java
  src/main/java/com/playdata/eungae/hospital/domain/Hospital.java
  src/main/java/com/playdata/eungae/hospital/repository/HospitalRepository.java
  src/main/java/com/playdata/eungae/member/controller/MemberApiController.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/domain/FavoritesHospital.java
  src/main/java/com/playdata/eungae/member/domain/Member.java
  src/main/java/com/playdata/eungae/member/dto/RequestFavoriesDto.java
  src/main/java/com/playdata/eungae/member/dto/SignUpMemberRequestDto.java
  src/main/java/com/playdata/eungae/member/repository/FavoritesHospitalRepository.java
  src/main/java/com/playdata/eungae/member/repository/MemberRepository.java
  src/main/java/com/playdata/eungae/member/service/MemberService.java
  src/main/java/com/playdata/eungae/review/service/ReviewService.java
  src/main/java/com/playdata/eungae/vo/Response.java
  src/test/java/com/playdata/eungae/member/service/MemberServiceTest.java
  src/test/java/com/playdata/eungae/review/service/ReviewServiceTest.java
Labels: 💻 백엔드, 🛠️ 리팩토링

#183 [BE] Fix: 자녀관리 기능 수정
  src/main/java/com/playdata/eungae/member/controller/ChildrenController.java
  src/main/java/com/playdata/eungae/member/domain/Children.java
  src/main/java/com/playdata/eungae/member/dto/ChildrenDto.java
  src/main/java/com/playdata/eungae/member/service/ChildrenService.java
  src/main/resources/static/js/my-children.js
  src/main/resources/templates/contents/member/my-children-add.html
  src/main/resources/templates/contents/member/my-children.html
Labels: 💻 백엔드

#184 [BE] Feat: 병원 상세보기 기능 구현
  src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
  src/main/java/com/playdata/eungae/doctor/dto/DoctorViewResponseDto.java
  src/main/java/com/playdata/eungae/doctor/repository/DoctorRepository.java
  src/main/java/com/playdata/eungae/doctor/service/DoctorService.java
  src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalScheduleViewResponseDto.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalViewResponseDto.java
  src/main/java/com/playdata/eungae/hospital/repository/HospitalRepository.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
Labels: 💻 백엔드

#186 [BE] Feat: 회원가입 실행 테스트
  src/main/java/com/playdata/eungae/HomeController.java
  src/main/java/com/playdata/eungae/config/WebSecurityConfig.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/domain/Member.java
  src/main/java/com/playdata/eungae/member/dto/SignUpMemberRequestDto.java
  src/main/java/com/playdata/eungae/member/service/MemberService.java
  src/main/resources/static/js/sign-up.js
  src/main/resources/templates/contents/member/sign-up.html
  src/test/java/com/playdata/eungae/member/service/MemberServiceTest.java
  src/test/java/com/playdata/eungae/review/service/ReviewServiceTest.java
Labels: 💻 백엔드, 📝 테스트

#187 [BE] Feat : 리뷰 Pagination API 개발
  src/main/java/com/playdata/eungae/appointment/domain/Appointment.java
  src/main/java/com/playdata/eungae/review/controller/ReviewApiController.java
  src/main/java/com/playdata/eungae/review/domain/Review.java
  src/main/java/com/playdata/eungae/review/dto/ResponseReviewDto.java
  src/main/java/com/playdata/eungae/review/repository/ReviewRepository.java
  src/main/java/com/playdata/eungae/review/service/ReviewService.java
  src/test/java/com/playdata/eungae/review/service/ReviewServiceTest.java
Labels: 💻 백엔드

#188 [FE] Feat: 병원 상세보기 페이지 DB데이터 적용
  src/main/resources/static/css/hospital-details.css
  src/main/resources/static/js/hospital-details.js
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 🎨 프론트엔드

#190 [BE] Refactor : Controller Return type response -> ResponseStatus
  src/main/java/com/playdata/eungae/appointment/domain/Appointment.java
  src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java
  src/main/java/com/playdata/eungae/config/WebSecurityConfig.java
  src/main/java/com/playdata/eungae/member/controller/MemberApiController.java
  src/main/java/com/playdata/eungae/member/domain/Children.java
  src/main/java/com/playdata/eungae/member/service/MemberService.java
  src/main/java/com/playdata/eungae/review/controller/ReviewApiController.java
  src/main/java/com/playdata/eungae/review/dto/RequestReviewFormDto.java
  src/main/java/com/playdata/eungae/review/repository/ReviewRepository.java
  src/main/java/com/playdata/eungae/review/service/ReviewService.java
  src/main/java/com/playdata/eungae/vo/Response.java
  src/test/java/com/playdata/eungae/member/service/MemberServiceTest.java
Labels: 💻 백엔드, 🛠️ 리팩토링

#189 [BE] Feat: 내 진료기록 전체 조회하기 기능
  src/main/java/com/playdata/eungae/appointment/dto/AppointmentResponseDto.java
  src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
Labels: 💻 백엔드

#191 [BE] Feat: 로그인 실행 테스트
  build.gradle
  src/main/java/com/playdata/eungae/HomeController.java
  src/main/java/com/playdata/eungae/config/WebSecurityConfig.java
  src/main/java/com/playdata/eungae/member/domain/Member.java
  src/main/java/com/playdata/eungae/member/service/MemberService.java
  src/main/resources/static/css/login.css
  src/main/resources/templates/contents/member/login.html
  src/main/resources/templates/fragments/mainHeader.html
  src/main/resources/templates/index.html
  src/test/java/com/playdata/eungae/member/service/MemberServiceTest.java
Labels: 💻 백엔드

#192 [BE] Feat: 회원 정보 수정 기능 구현
  src/main/java/com/playdata/eungae/article/controller/NoticeViewController.java
  src/main/java/com/playdata/eungae/member/controller/MemberApiController.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/dto/MemberUpdateRequestDto.java
  src/main/java/com/playdata/eungae/member/dto/MemberUpdateResponseDto.java
  src/main/java/com/playdata/eungae/member/repository/MemberRepository.java
  src/main/java/com/playdata/eungae/member/service/MemberService.java
  src/main/resources/static/css/my-page-form.css
  src/main/resources/static/css/notice-list.css
  src/main/resources/static/js/my-page-form.js
  src/main/resources/static/js/my-page.js
  src/main/resources/templates/contents/member/my-page-form.html
  src/main/resources/templates/contents/member/my-page.html
  src/main/resources/templates/contents/notice/notice-list.html
Labels: 💻 백엔드

#193 [BE] Feat: 병원 상세보기 기능 구현
  src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
  src/main/java/com/playdata/eungae/doctor/repository/DoctorRepository.java
  src/main/java/com/playdata/eungae/doctor/service/DoctorService.java
Labels: 💻 백엔드

#198 [BE] Feat: initDB dummy 데이터 생성
  src/main/java/com/playdata/eungae/initDB.java
  src/main/java/com/playdata/eungae/member/controller/MemberApiController.java
  src/test/java/com/playdata/eungae/member/service/MemberServiceTest.java
Labels: 💻 백엔드

#199 [BE] Feat: initDB dummy 데이터 생성, 발표 준비
  src/main/java/com/playdata/eungae/initDB.java
  src/main/resources/static/img/jbj.png
  src/main/resources/static/img/kwj.jpg
  src/main/resources/static/js/hospital-details.js
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 💻 백엔드, 🎨 프론트엔드

#208 [BE] Feat: 예약을 위한 세팅 및 공공데이터 파싱 코드 작성
  src/main/java/com/playdata/eungae/admin/controller/AdminController.java
  src/main/java/com/playdata/eungae/admin/service/AdminService.java
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/java/com/playdata/eungae/appointment/dto/AppointmentRequestDto.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
  src/main/java/com/playdata/eungae/doctor/repository/DoctorRepository.java
  src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java
  src/main/java/com/playdata/eungae/hospital/domain/Hospital.java
  src/main/java/com/playdata/eungae/hospital/domain/HospitalSchedule.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalViewResponseDto.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
  src/main/java/com/playdata/eungae/initDB.java
  src/main/java/com/playdata/eungae/member/controller/ChildrenController.java
  src/main/java/com/playdata/eungae/member/dto/ChildrenDto.java
  src/main/java/com/playdata/eungae/member/dto/SignUpMemberRequestDto.java
  src/main/java/com/playdata/eungae/member/repository/ChildrenRepository.java
  src/main/java/com/playdata/eungae/member/service/ChildrenService.java
  src/main/resources/application.yml
  src/main/resources/static/css/appointment.css
  src/main/resources/static/js/appointment.js
  src/main/resources/static/js/map.js
  src/main/resources/templates/contents/appointment/appointment.html
  src/main/resources/templates/contents/hospital/hospital-details.html
  src/test/java/com/playdata/eungae/hospital/service/HospitalServiceImplTest.java
Labels: 💻 백엔드, 🛠️ 리팩토링

#210 [BE] Feat: 내 주변 병원 찾기 API 개발
  src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalSearchResponseDto.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
Labels: 💻 백엔드

#213 [ALL] Feat: 의사, 병원 이미지 파일 업로드, 의사 생성 기능 구현 및 화면 연결
  src/main/java/com/playdata/eungae/config/SpringConfig.java
  src/main/java/com/playdata/eungae/doctor/controller/DoctorViewController.java
  src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
  src/main/java/com/playdata/eungae/doctor/dto/DoctorRegisterRequestDto.java
  src/main/java/com/playdata/eungae/doctor/service/DoctorService.java
  src/main/java/com/playdata/eungae/file/FileStore.java
  src/main/java/com/playdata/eungae/file/ResultFileStore.java
  src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java
  src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java
  src/main/java/com/playdata/eungae/hospital/domain/Hospital.java
  src/main/java/com/playdata/eungae/hospital/domain/HospitalImage.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalImageResponseDto.java
  src/main/java/com/playdata/eungae/hospital/repository/HospitalImageRepository.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalImageService.java
  src/main/java/com/playdata/eungae/initDB.java
  src/main/java/com/playdata/eungae/review/controller/ReviewApiController.java
  src/main/java/com/playdata/eungae/review/dto/ResponseReviewDto.java
  src/main/java/com/playdata/eungae/review/repository/ReviewRepository.java
  src/main/java/com/playdata/eungae/review/service/ReviewService.java
  src/main/resources/application.yml
  src/main/resources/static/css/hospital-details.css
  src/main/resources/static/js/hospital-details.js
  src/main/resources/static/js/map.js
  src/main/resources/templates/contents/hospital/create-doctor.html
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 💻 백엔드, 🎨 프론트엔드

#207 [BE] Feat : 예약 내역 페이지네이션 기능 추가
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
  src/main/java/com/playdata/eungae/appointment/domain/Appointment.java
  src/main/java/com/playdata/eungae/appointment/dto/ResponseAppointmentDto.java
  src/main/java/com/playdata/eungae/appointment/dto/ResponseDetailMedicalHistoryDto.java
  src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/member/domain/Children.java
  src/main/java/com/playdata/eungae/member/domain/Member.java
  src/main/java/com/playdata/eungae/review/service/ReviewService.java
Labels: 💻 백엔드

#215 [ALL] Feat: 마이페이지 및 회원정보 수정 기능 구현 및 화면 연결
  src/main/java/com/playdata/eungae/member/controller/MemberApiController.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/domain/Member.java
  src/main/java/com/playdata/eungae/member/dto/MemberFindResponseDto.java
  src/main/java/com/playdata/eungae/member/dto/MemberUpdateRequestDto.java
  src/main/java/com/playdata/eungae/member/dto/MemberUpdateResponseDto.java
  src/main/java/com/playdata/eungae/member/repository/MemberRepository.java
  src/main/java/com/playdata/eungae/member/service/MemberService.java
  src/main/resources/static/js/my-page-form.js
  src/main/resources/static/js/my-page.js
  src/main/resources/templates/contents/member/my-page.html
Labels: 💻 백엔드, 🎨 프론트엔드

#218 [ALL] Feat: 내 주변 병원찾기 기능 추가
  src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalSearchResponseDto.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
  src/main/java/com/playdata/eungae/initDB.java
  src/main/resources/static/js/map.js
  src/main/resources/templates/contents/hospital/find-hospital.html
Labels: 💻 백엔드, 🎨 프론트엔드

#220 [ALL] Feat: 공지사항 목록 및 공지사항 상세 기능 구현 및 화면 연결
  src/main/java/com/playdata/eungae/article/controller/NoticeViewController.java
  src/main/java/com/playdata/eungae/article/domain/Notice.java
  src/main/java/com/playdata/eungae/article/dto/NoticeListResponseDto.java
  src/main/java/com/playdata/eungae/article/dto/NoticeResponseDto.java
  src/main/java/com/playdata/eungae/article/repository/NoticeRepository.java
  src/main/java/com/playdata/eungae/article/service/NoticeService.java
  src/main/java/com/playdata/eungae/initDB.java
  src/main/resources/static/css/notice-details.css
  src/main/resources/templates/contents/notice/notice-details.html
  src/main/resources/templates/contents/notice/notice-list.html
  src/main/resources/templates/fragments/mainHeader.html
Labels: 💻 백엔드, 🎨 프론트엔드

#221 [BE] Feat: Merge 후 오류 수정
  src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/config/SpringConfig.java
  src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
  src/main/java/com/playdata/eungae/initDB.java
Labels: 🚨 버그

#222 [BE 긴급!] Feat : Appointment 기능 개발중
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
  src/main/java/com/playdata/eungae/appointment/domain/Appointment.java
  src/main/java/com/playdata/eungae/appointment/dto/AppointmentRequestDto.java
  src/main/java/com/playdata/eungae/appointment/dto/AppointmentResponseDto.java
  src/main/java/com/playdata/eungae/appointment/dto/AppointmentTimeResponseDto.java
  src/main/java/com/playdata/eungae/appointment/dto/ResponseAppointmentDto.java
  src/main/java/com/playdata/eungae/appointment/dto/ResponseDetailMedicalHistoryDto.java
  src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/hospital/repository/HospitalScheduleRepository.java
  src/main/java/com/playdata/eungae/initDB.java
Labels: 💻 백엔드

#225 [BE] Fix: 이미지 업로드 코드 리팩토링
  src/main/java/com/playdata/eungae/config/FileUploadConfig.java
  src/main/java/com/playdata/eungae/doctor/controller/DoctorViewController.java
  src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
  src/main/java/com/playdata/eungae/doctor/dto/DoctorRegisterRequestDto.java
  src/main/java/com/playdata/eungae/doctor/dto/DoctorViewResponseDto.java
  src/main/java/com/playdata/eungae/doctor/service/DoctorService.java
  src/main/java/com/playdata/eungae/file/FileStore.java
  src/main/java/com/playdata/eungae/file/ResultFileStore.java
  src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java
  src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalImageService.java
  src/main/java/com/playdata/eungae/initDB.java
  src/main/resources/application.yml
Labels: 💻 백엔드, 🛠️ 리팩토링

#216 [BE] Feat: CommunityBoard 개발
  src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java
  src/main/java/com/playdata/eungae/article/domain/CommunityBoard.java
  src/main/java/com/playdata/eungae/article/dto/CommunityBoardDto.java
  src/main/java/com/playdata/eungae/article/repository/CommunityBoardRepository.java
  src/main/java/com/playdata/eungae/article/service/CommunityBoardService.java
  src/main/resources/templates/contents/community/community-list.html
  src/main/resources/templates/contents/community/community-write.html
Labels: 💻 백엔드

#226 [BE] Feat: 병원 검색 API 개발
  src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java
  src/main/java/com/playdata/eungae/hospital/repository/HospitalRepository.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
Labels: 💻 백엔드

#229 [FE] Feat: 병원 상세페이지 이미지 슬라이드 구현
  src/main/resources/static/css/hospital-details.css
  src/main/resources/static/js/hospital-details.js
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 🎨 프론트엔드

#234 [BE] Fix: 공지사항 목록 및 공지사항 상세 기능 수정
  src/main/java/com/playdata/eungae/article/controller/NoticeViewController.java
Labels: 💻 백엔드

#237 [ALL] Feat: 내 리뷰목록 페이지 화면 매핑
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/resources/static/css/review-write.css
  src/main/resources/templates/contents/member/my-review.html
  src/main/resources/templates/contents/member/review-write.html
Labels: 💻 백엔드, 🎨 프론트엔드

#239 [ALL] Feat: 병원 상세보기 화면 연결
  src/main/java/com/playdata/eungae/hospital/dto/HospitalViewResponseDto.java
  src/main/resources/templates/contents/hospital/hospital-details.html
  src/main/resources/templates/fragments/hospitalBottomNavbar.html
  src/main/resources/templates/layouts/hosptial_detail_layout.html
Labels: 💻 백엔드, 🎨 프론트엔드

#230 [BE] Feat: 예약 기능 개발 완료, 정상케이스만 테스트
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/java/com/playdata/eungae/appointment/dto/AppointmentRequestDto.java
  src/main/java/com/playdata/eungae/appointment/dto/ResponseAppointmentDto.java
  src/main/java/com/playdata/eungae/appointment/dto/ResponseDetailMedicalHistoryDto.java
  src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/config/WebSecurityConfig.java
  src/main/java/com/playdata/eungae/initDB.java
  src/main/resources/static/js/appointment.js
  src/main/resources/static/js/map.js
  src/main/resources/templates/contents/appointment/appointment.html
Labels: 💻 백엔드, 🛠️ 리팩토링

#241 [FE] Feat: 병원 이미지 기본 화면 구현
  src/main/resources/static/css/hospital-details.css
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 🎨 프론트엔드

#242 [ALL] Feat : Review 등록 기능 추가
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/java/com/playdata/eungae/appointment/dto/AppointmentResponseDto.java
  src/main/java/com/playdata/eungae/appointment/dto/ResponseDetailMedicalHistoryDto.java
  src/main/java/com/playdata/eungae/appointment/dto/ResponseMedicalHistoryDto.java
  src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/hospital/domain/Hospital.java
  src/main/java/com/playdata/eungae/initDB.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/domain/Children.java
  src/main/java/com/playdata/eungae/review/controller/ReviewApiController.java
  src/main/java/com/playdata/eungae/review/controller/ReviewViewController.java
  src/main/java/com/playdata/eungae/review/domain/Review.java
  src/main/java/com/playdata/eungae/review/dto/RequestReviewFormDto.java
  src/main/java/com/playdata/eungae/review/dto/ResponseReviewDto.java
  src/main/java/com/playdata/eungae/review/repository/ReviewRepository.java
  src/main/java/com/playdata/eungae/review/service/ReviewService.java
  src/main/resources/templates/contents/member/medical-records-details.html
  src/main/resources/templates/contents/member/medical-records.html
  src/main/resources/templates/contents/member/my-review.html
  src/main/resources/templates/contents/member/review-write.html
Labels: 💻 백엔드, 🎨 프론트엔드

#244 [BE] Fix: 병합 이후 오류 수정
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/initDB.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
Labels: 🚨 버그

#254 [FE] Feat: 병원 상세 페이지 즐겨찾기 버튼 추가
  src/main/resources/static/css/hospital-details.css
  src/main/resources/static/js/hospital-details.js
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 🎨 프론트엔드

#247 [ALL] Feat : 내 예약 조회, 예약 취소, 리뷰 등록, 진료내역 조회 개발 완료
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
  src/main/java/com/playdata/eungae/appointment/domain/Appointment.java
  src/main/java/com/playdata/eungae/appointment/dto/AppointmentRequestDto.java
  src/main/java/com/playdata/eungae/appointment/dto/RequestAppointmentDeleteDto.java
  src/main/java/com/playdata/eungae/appointment/dto/ResponseAppointmentDto.java
  src/main/java/com/playdata/eungae/appointment/dto/ResponseDetailMedicalHistoryDto.java
  src/main/java/com/playdata/eungae/appointment/dto/ResponseMedicalHistoryDto.java
  src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/review/controller/ReviewViewController.java
  src/main/resources/static/css/medical-records.css
  src/main/resources/static/css/my-reservations.css
  src/main/resources/static/js/my-reservations.js
  src/main/resources/templates/contents/member/medical-records-details.html
  src/main/resources/templates/contents/member/medical-records.html
  src/main/resources/templates/contents/member/my-reservations.html
  src/main/resources/templates/contents/member/my-review.html
  src/main/resources/templates/contents/member/review-write.html
Labels: 💻 백엔드, 🎨 프론트엔드

#245 [BE] Fix: 공지사항 기능 수정
  src/main/java/com/playdata/eungae/article/controller/NoticeViewController.java
  src/main/java/com/playdata/eungae/article/dto/NoticeListResponseDto.java
  src/main/java/com/playdata/eungae/article/dto/NoticeResponseDto.java
  src/main/java/com/playdata/eungae/article/service/NoticeService.java
Labels: 💻 백엔드

#246 [BE] Fix: 마이페이지 및 회원정보 수정 기능 수정
  src/main/java/com/playdata/eungae/member/controller/MemberApiController.java
  src/main/java/com/playdata/eungae/member/service/MemberService.java
Labels: 💻 백엔드, 🛠️ 리팩토링

#250 [ALL] Feat: GlobalExceptionHandler 구현
  src/main/java/com/playdata/eungae/exception/GlobalExceptionHandler.java
  src/main/resources/static/img/404.png
  src/main/resources/static/img/500.png
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/500.html
Labels: 💻 백엔드, 🎨 프론트엔드

#251 [BE] Fix: 이미지 코드 리팩토링
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/config/WebConfig.java
  src/main/java/com/playdata/eungae/doctor/controller/DoctorViewController.java
  src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
  src/main/java/com/playdata/eungae/doctor/dto/DoctorRegisterRequestDto.java
  src/main/java/com/playdata/eungae/doctor/dto/DoctorResponseDto.java
  src/main/java/com/playdata/eungae/doctor/repository/DoctorRepository.java
  src/main/java/com/playdata/eungae/doctor/service/DoctorService.java
  src/main/java/com/playdata/eungae/file/FileStore.java
  src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java
  src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalSearchResponseDto.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalViewResponseDto.java
  src/main/java/com/playdata/eungae/hospital/repository/HospitalRepository.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalImageService.java
  src/main/java/com/playdata/eungae/initDB.java
Labels: 💻 백엔드, 🛠️ 리팩토링

#255 [FE] Feat: 병원 검색결과 프론트 연결
  src/main/resources/static/js/map.js
Labels: 🎨 프론트엔드

#257 [BE] Feat: CommunityBoard Controller 누락된 거 다시 PR
  src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java
Labels: 💻 백엔드

#259 [FE] Feat: 병원 검색시 공백확인
  src/main/resources/static/js/map.js
Labels: 🎨 프론트엔드

#261 [ALL] Refactor : review, appointment 코드 리펙터링
  src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/member/controller/MemberApiController.java
  src/main/java/com/playdata/eungae/member/repository/FavoritesHospitalRepository.java
  src/main/java/com/playdata/eungae/member/service/MemberService.java
  src/main/java/com/playdata/eungae/review/controller/ReviewViewController.java
  src/main/java/com/playdata/eungae/review/repository/ReviewRepository.java
  src/main/java/com/playdata/eungae/review/service/ReviewService.java
  src/main/resources/static/js/hospital-details.js
Labels: 💻 백엔드, 🛠️ 리팩토링, 🎨 프론트엔드

#271 [ALL] Fix: 주변 병원검색 latitude와 longtude 변경
  src/main/resources/static/js/map.js
Labels: 💻 백엔드, 🎨 프론트엔드

#266 [BE] Feat: 의사 삭제 기능 구현
  src/main/java/com/playdata/eungae/base/BaseEntity.java
  src/main/java/com/playdata/eungae/doctor/controller/DoctorViewController.java
  src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
  src/main/java/com/playdata/eungae/doctor/dto/DoctorRegisterRequestDto.java
  src/main/java/com/playdata/eungae/doctor/service/DoctorService.java
  src/main/java/com/playdata/eungae/initDB.java
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 💻 백엔드

#273 [FE] Fix: 병원 상세보기 이미지 슬라이드 수정
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 🎨 프론트엔드

#274 [BE] Feat: CommunityBoard 맵핑,글쓰기, 삭제, 상세보기 개발 및 자녀 기능 수정
  src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java
  src/main/java/com/playdata/eungae/article/dto/CommunityBoardDto.java
  src/main/java/com/playdata/eungae/member/controller/ChildrenController.java
  src/main/resources/static/js/community-list.js
  src/main/resources/templates/contents/community/community-list.html
  src/main/resources/templates/contents/community/community-post-details.html
  src/main/resources/templates/contents/community/community-write.html
  src/main/resources/templates/contents/member/my-children-add.html
  src/main/resources/templates/fragments/bottomNavbar.html
Labels: 💻 백엔드

#275 [ALL] Feat : appointment 창에서 정보 수정시 api 요청 보내도록 수정
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/domain/Children.java
  src/main/resources/static/css/appointment.css
  src/main/resources/static/js/appointment.js
  src/main/resources/templates/contents/appointment/appointment.html
Labels: 💻 백엔드, 🎨 프론트엔드

#277 [FE] Fix: 카카오맵 마커 오버레이 에러 수정
  src/main/resources/static/js/map.js
Labels: 🚨 버그, 🎨 프론트엔드

#279 [FE] Fix: 지도 자바스크립트 수정
  src/main/java/com/playdata/eungae/initDB.java
  src/main/resources/static/js/hospital-details.js
Labels: 🎨 프론트엔드

#280 [ALL] Feat : 유효성 검사 추가
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/resources/static/js/appointment.js
  src/main/resources/templates/contents/appointment/appointment.html
Labels: 💻 백엔드, 🎨 프론트엔드

#282 [ALL] Feat: 단골 병원 DB 데이터 화면과 연결
  src/main/java/com/playdata/eungae/member/dto/ResponseFavoritesHospitalDto.java
  src/main/resources/static/css/regular-hospital.css
  src/main/resources/templates/contents/member/regular-hospital.html
Labels: 💻 백엔드, 🎨 프론트엔드

#285 [FE] Fix: 메인페이지 화면 수정
  src/main/resources/static/css/main.css
  src/main/resources/templates/index.html
Labels: 🎨 프론트엔드

#289 [BE] Feat: 병원 키워드검색 유효성 검사
  src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java
Labels: 💻 백엔드

#290 [BE] Feat: 환자 방문 여부 체크
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
  src/main/java/com/playdata/eungae/appointment/dto/VisitedChangeStatusDto.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
Labels: 💻 백엔드

#291 [ALL] Fix : Review가 없으면 병원 상세페이지가 표시되지 않는 버그 수정
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/member/repository/ChildrenRepository.java
  src/main/java/com/playdata/eungae/review/service/ReviewService.java
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 💻 백엔드, 🚨 버그, 🎨 프론트엔드

#294 [ALL] Feat: 병원 메인 레이아웃 및 매핑
  src/main/java/com/playdata/eungae/doctor/controller/DoctorViewController.java
  src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java
  src/main/resources/static/css/hospital-admin-doctor-form.css
  src/main/resources/static/css/hospital-shared.css
  src/main/resources/static/img/logo4.png
  src/main/resources/templates/contents/hospital/create-doctor.html
  src/main/resources/templates/fragments/hospital/hospital-footer.html
  src/main/resources/templates/fragments/hospital/hospital-header.html
  src/main/resources/templates/fragments/hospital/hospital-navbar.html
  src/main/resources/templates/hospital-contents/hospital-admin-doctor-form.html
  src/main/resources/templates/hospital-contents/hospital-admin.html
  src/main/resources/templates/layouts/hosptial_main_layout.html
Labels: 💻 백엔드, 🎨 프론트엔드

#297 [BE] Refactor: 코드 포맷팅 및 리뷰 사항 반영
  src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
Labels: 💻 백엔드, 🛠️ 리팩토링

#302 [FE] Fix: 메인페이지 버튼 연결 수정
  src/main/resources/templates/index.html
Labels: 🎨 프론트엔드

#299 [BE] Refactor: 소아과만 파싱하도록 변경
  README.md
  src/main/java/com/playdata/eungae/admin/service/AdminService.java
  src/main/resources/application.yml
Labels: 📃 문서, 💻 백엔드, 🛠️ 리팩토링

#306 [BE] Fix: AWS 배포 후 gradle 빌드 도중 작성된 Test 코드에서 컴파일 에러가 발생했습니다.
  src/test/java/com/playdata/eungae/member/service/MemberServiceTest.java
  src/test/java/com/playdata/eungae/review/service/ReviewServiceTest.java
Labels: 🚨 버그, 📝 테스트

#304 [FE] Feat: 다른 마커 선택시 다른 오버레이 지우기
  src/main/resources/static/js/map.js
Labels: 🎨 프론트엔드

#292 [ALL] Feat:CommunityBoard 수정기능 추가, ChildrenController 삭제, MemberViewController 리팩토링
  src/main/java/com/playdata/eungae/EungaeApplication.java
  src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java
  src/main/java/com/playdata/eungae/article/domain/CommunityBoard.java
  src/main/java/com/playdata/eungae/article/dto/CommunityBoardDto.java
  src/main/java/com/playdata/eungae/article/repository/CommunityBoardRepository.java
  src/main/java/com/playdata/eungae/article/service/CommunityBoardService.java
  src/main/java/com/playdata/eungae/member/controller/ChildrenController.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/service/ChildrenService.java
  src/main/resources/application.yml
  src/main/resources/static/js/community-list.js
  src/main/resources/templates/contents/community/community-edit.html
  src/main/resources/templates/contents/community/community-post-details.html
  src/main/resources/templates/contents/member/my-children-add.html
  src/main/resources/templates/contents/member/my-children.html
  src/main/resources/templates/contents/member/my-page.html
Labels: 💻 백엔드, 🎨 프론트엔드

#316 [FE] Fix : 즐겨찾기 추가시 css가 변경되지 않던 문제 해결
  src/main/java/com/playdata/eungae/member/controller/MemberApiController.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/resources/static/js/appointment.js
  src/main/resources/static/js/hospital-details.js
  src/main/resources/templates/contents/appointment/appointment.html
Labels: 🎨 프론트엔드

#309 [BE] Fix: 회원가입 정규 표현식 추가
  src/main/java/com/playdata/eungae/member/domain/Member.java
  src/main/java/com/playdata/eungae/member/dto/SignUpMemberRequestDto.java
  src/main/resources/templates/contents/member/sign-up.html
Labels: 💻 백엔드, 🚨 버그, 🎨 프론트엔드

#312 [FE] Feat: 병원 수정 페이지 작업
  src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java
  src/main/resources/static/css/hospital-shared.css
  src/main/resources/static/css/hospital-update.css
  src/main/resources/static/img/github-mark.png
  src/main/resources/static/js/hospital-update.js
  src/main/resources/templates/fragments/hospital/hospital-footer.html
  src/main/resources/templates/fragments/hospital/hospital-navbar.html
  src/main/resources/templates/hospital-contents/hospital-admin-doctor-form.html
  src/main/resources/templates/hospital-contents/hospital-admin.html
  src/main/resources/templates/hospital-contents/hospital-update.html
Labels: 🎨 프론트엔드

#317 [BE] Fix: 병합 후 오류 수정
  src/main/java/com/playdata/eungae/member/service/ChildrenService.java
Labels: 💻 백엔드, 🚨 버그

#321 [BE] Fix: 병합 후 오류 수정
  src/main/java/com/playdata/eungae/initDB.java
  src/main/java/com/playdata/eungae/member/domain/Member.java
Labels: 💻 백엔드, 🚨 버그

#322 [BE] Feat: initDB 수정
  src/main/java/com/playdata/eungae/initDB.java
Labels: 💻 백엔드

#320 [ALL] Feat: 병원 검색 이후 지도 중심 변경
  src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java
  src/main/java/com/playdata/eungae/hospital/dto/KeywordSearchRequestDto.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
  src/main/resources/static/js/map.js
Labels: 💻 백엔드, 🎨 프론트엔드

#323 [BE] Fix: 메인에서 articles 경로 수정,예약에서 자녀 추가 경로 수정, 자녀 리스트 연도 표시 수정
  src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java
  src/main/java/com/playdata/eungae/member/service/ChildrenService.java
  src/main/resources/templates/contents/appointment/appointment.html
  src/main/resources/templates/fragments/mainHeader.html
Labels: 🛠️ 리팩토링

#325 [ALL] Feat: 병원 검색 리스트 화면 연결
  src/main/java/com/playdata/eungae/HomeController.java
  src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalSearchResponseDto.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
  src/main/resources/templates/contents/hospital/search-hospital.html
  src/main/resources/templates/index.html
Labels: 💻 백엔드, 🎨 프론트엔드

#326 [ALL] Feat : View Controller 유효성 검사 추가
  src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java
  src/main/java/com/playdata/eungae/article/domain/CommunityBoard.java
  src/main/java/com/playdata/eungae/article/dto/CommunityBoardDto.java
  src/main/java/com/playdata/eungae/article/repository/CommunityBoardRepository.java
  src/main/java/com/playdata/eungae/article/service/CommunityBoardService.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/domain/Member.java
  src/main/java/com/playdata/eungae/member/dto/ChildrenRequestDto.java
  src/main/java/com/playdata/eungae/member/service/ChildrenService.java
  src/main/java/com/playdata/eungae/review/controller/ReviewViewController.java
  src/main/java/com/playdata/eungae/review/dto/RequestReviewFormDto.java
  src/main/resources/static/css/shared.css
  src/main/resources/templates/contents/community/community-edit.html
  src/main/resources/templates/contents/community/community-list.html
  src/main/resources/templates/contents/community/community-write.html
  src/main/resources/templates/contents/member/my-children-add.html
  src/main/resources/templates/contents/member/review-write.html
Labels: 💻 백엔드, 🛠️ 리팩토링, 🎨 프론트엔드

#329 [FE] Feat: hospital의 addressDetail 필드가 thymeleaf에서 랜더링 되지 않게 수정
  src/main/resources/static/js/map.js
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 🎨 프론트엔드

#330 [FE] Refactor: 이미지 슬라이드 수정
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 🎨 프론트엔드

#331 [FE] Fix: 의사 기본 이미지 처리
  src/main/resources/static/css/appointment.css
  src/main/resources/templates/contents/appointment/appointment.html
Labels: 🎨 프론트엔드

#333 [BE] Fix: Hospital 컨트롤러, 서비스 메소드명 수정, KeywordSearchRequestDto 수정
  src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java
  src/main/java/com/playdata/eungae/hospital/dto/KeywordSearchRequestDto.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
Labels: 💻 백엔드

#336 [BE] Fix: 병합 과정에서 발생한 에러 해결 및 Entity를 View에 직접 반환하는 로직 변경
  src/main/java/com/playdata/eungae/admin/service/AdminService.java
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java
  src/main/java/com/playdata/eungae/config/SpringConfig.java
  src/main/java/com/playdata/eungae/config/WebSecurityConfig.java
  src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java
  src/main/resources/application.yml
Labels: 💻 백엔드, 🚨 버그, 🛠️ 리팩토링

#335 [FE] Refactor : 전체 코드 리펙토링 & JPA 로직 최적화
  src/main/java/com/playdata/eungae/EungaeApplication.java
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java
  src/main/java/com/playdata/eungae/article/repository/CommunityBoardRepository.java
  src/main/java/com/playdata/eungae/article/service/CommunityBoardService.java
  src/main/java/com/playdata/eungae/article/service/NoticeService.java
  src/main/java/com/playdata/eungae/config/SpringConfig.java
  src/main/java/com/playdata/eungae/doctor/service/DoctorService.java
  src/main/java/com/playdata/eungae/hospital/repository/HospitalRepository.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/service/ChildrenService.java
  src/main/java/com/playdata/eungae/review/service/ReviewService.java
  src/main/resources/static/js/my-reservations.js
Labels: 💻 백엔드, 🛠️ 리팩토링, 🎨 프론트엔드

#339 [ALL] Feat: 예약 현재 시간 이전 시간 비활성화
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/resources/static/js/appointment.js
Labels: 💻 백엔드, 🎨 프론트엔드

#341 [ALL] Fix: 커뮤니티 css, 매핑 오류 수정
  src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java
  src/main/resources/static/css/community-list.css
  src/main/resources/static/css/medical-records-details.css
  src/main/resources/templates/contents/community/community-edit.html
  src/main/resources/templates/contents/community/community-list.html
  src/main/resources/templates/contents/community/community-post-details.html
  src/main/resources/templates/contents/member/regular-hospital.html
Labels: 💻 백엔드, 🚨 버그, 🎨 프론트엔드

#344 [BE] Feat: DoctorStatus 엔티티 추가
  src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
  src/main/java/com/playdata/eungae/doctor/domain/DoctorStatus.java
  src/main/java/com/playdata/eungae/doctor/dto/DoctorResponseDto.java
Labels: 💻 백엔드

#347 [BE] Fix: 회원 정보 수정 코드 리팩토링
  src/main/java/com/playdata/eungae/article/controller/ArticleViewController.java
  src/main/java/com/playdata/eungae/doctor/controller/DoctorViewController.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/domain/Member.java
  src/main/java/com/playdata/eungae/member/dto/MemberInfoResponseDto.java
  src/main/java/com/playdata/eungae/member/dto/MemberUpdateResponseDto.java
  src/main/java/com/playdata/eungae/member/service/MemberService.java
Labels: 💻 백엔드, 🛠️ 리팩토링

#348 [ALL] Feat : 결제 기능 추가
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/java/com/playdata/eungae/appointment/dto/ResponsePaymentDto.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/resources/static/js/appointment.js
  src/main/resources/templates/contents/appointment/appointment.html
Labels: 💻 백엔드, 🎨 프론트엔드

#349 [BE] Fix: 병합 후 발생하는 에러 수정
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
Labels: 💻 백엔드

#350 [ALL] Feat : doctor status가 on인 doctor의 정보만 화면에 반환하도록 로직 변경
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/doctor/repository/DoctorRepository.java
  src/main/java/com/playdata/eungae/doctor/service/DoctorService.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/repository/ChildrenRepository.java
  src/main/java/com/playdata/eungae/review/controller/ReviewApiController.java
  src/main/java/com/playdata/eungae/review/repository/ReviewRepository.java
  src/main/java/com/playdata/eungae/review/service/ReviewService.java
  src/main/resources/static/js/appointment.js
  src/main/resources/templates/contents/member/my-review.html
Labels: 💻 백엔드, 🛠️ 리팩토링, 🎨 프론트엔드

#351 [BE] Feat: 주변 병원검색시 Redis에서 조회
  build.gradle
  src/main/java/com/playdata/eungae/admin/controller/AdminController.java
  src/main/java/com/playdata/eungae/admin/service/AdminService.java
  src/main/java/com/playdata/eungae/config/RedisConfig.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalSearchResponseDto.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
  src/main/resources/application.yml
Labels: 💻 백엔드

#352 [BE] Style: Kakao Api 인증키 추가 및 코드 포맷팅
  src/main/java/com/playdata/eungae/admin/service/AdminService.java
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
  src/main/java/com/playdata/eungae/appointment/domain/Appointment.java
  src/main/java/com/playdata/eungae/appointment/dto/AppointmentRequestDto.java
  src/main/java/com/playdata/eungae/appointment/dto/RequestAppointmentDeleteDto.java
  src/main/java/com/playdata/eungae/appointment/dto/ResponseMedicalHistoryDto.java
  src/main/resources/application.yml
Labels: 💻 백엔드

#355 [ALL] Feat : 결제시 LocalTime 객체가 json으로 변경되지 않아 발생하는 문제 해결
  src/main/java/com/playdata/eungae/admin/service/AdminService.java
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
Labels: 💻 백엔드

#358 [BE] Style: 카카오맵 오버레이 스타일 변경 및 나의 예약 페이지 스타일 변경
  src/main/java/com/playdata/eungae/HomeController.java
  src/main/java/com/playdata/eungae/initDB.java
  src/main/resources/application.yml
  src/main/resources/static/css/map.css
  src/main/resources/static/css/my-reservations.css
  src/main/resources/static/js/map.js
  src/main/resources/templates/contents/member/my-reservations.html
Labels: 🎨 프론트엔드

#362 [BE] Feat: 카카오 로그인 구현 완료
  build.gradle
  src/main/java/com/playdata/eungae/config/SecurityConfig.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/domain/Member.java
  src/main/java/com/playdata/eungae/security/KakaoUserInfo.java
  src/main/java/com/playdata/eungae/security/MemberOAuthUserService.java
  src/main/java/com/playdata/eungae/security/MemberUserDetails.java
  src/main/java/com/playdata/eungae/security/MemberUserDetailsService.java
  src/main/java/com/playdata/eungae/security/OAuthUserInfo.java
  src/main/resources/application.yml
  src/main/resources/static/js/kakao-login.js
  src/main/resources/templates/contents/member/login.html
Labels: 💻 백엔드

#364 [ALL] Feat : paymentResult 생성 메소드 이름 변경
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/java/com/playdata/eungae/appointment/dto/PaymentResultDto.java
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 💻 백엔드

#367 [FE] Fix: 내 리뷰목록에 제목이 뜨게 수정
  src/main/resources/templates/contents/member/my-review.html
Labels: 🎨 프론트엔드

#370 [BE] Fix: 로그인시 첫 번째 로그인일 경우 error 페이지가 랜더링 되는 에러 수정
  src/main/java/com/playdata/eungae/config/SecurityConfig.java
Labels: 💻 백엔드, 🚨 버그

#371 [BE] Fix : 예약시 LocalDate 타입의 json 파싱이 안되는 버그 수정
  src/main/java/com/playdata/eungae/appointment/dto/AppointmentRequestDto.java
  src/main/java/com/playdata/eungae/appointment/dto/ResponsePaymentDto.java
Labels: 💻 백엔드, 🚨 버그, 🎨 프론트엔드

#372 [FE] Style: 예약창 스타일 수정
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
  src/main/java/com/playdata/eungae/config/SecurityConfig.java
  src/main/java/com/playdata/eungae/initDB.java
  src/main/resources/static/css/appointment.css
  src/main/resources/static/css/hospital-details.css
  src/main/resources/static/css/regular-hospital.css
  src/main/resources/static/css/search-hospital.css
  src/main/resources/static/css/shared.css
  src/main/resources/templates/contents/appointment/appointment.html
  src/main/resources/templates/fragments/header.html
Labels: 💻 백엔드, 🎨 프론트엔드

#375 [ALL] Feat: 병원 검색시 대기자 수 확인
  src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalSearchResponseDto.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
  src/main/resources/static/css/map.css
  src/main/resources/static/js/map.js
Labels: 💻 백엔드, 🎨 프론트엔드

#377 [BE] Fix: 예약분류 컬럼 추가 (예약/현장등록)
  src/main/java/com/playdata/eungae/admin/service/AdminService.java
  src/main/java/com/playdata/eungae/appointment/domain/Appointment.java
  src/main/java/com/playdata/eungae/appointment/domain/AppointmentSort.java
  src/main/java/com/playdata/eungae/initDB.java
  src/main/java/com/playdata/eungae/security/MemberUserDetails.java
Labels: 💻 백엔드

#380 [BE] Fix: initDb 컴파일 에러 수정
  src/main/java/com/playdata/eungae/initDB.java
Labels: 💻 백엔드

#379 [BE] Fix: HospitalService 대기자 수 검색
  src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
Labels: 💻 백엔드, 🚨 버그

#383 [ALL] Fix: 지도 오버레이 이미지 수정 및 레디스 환경 변수 변경
  src/main/java/com/playdata/eungae/config/RedisConfig.java
  src/main/java/com/playdata/eungae/config/SecurityConfig.java
  src/main/java/com/playdata/eungae/config/SpringConfig.java
  src/main/java/com/playdata/eungae/initDB.java
  src/main/resources/application.yml
  src/main/resources/static/js/map.js
Labels: 💻 백엔드, 🛠️ 리팩토링
