Repository team-eungae/eungae-pediatric_appointment, pull requests merged in 2024-02, with the labels that each got.

#387 [BE] Fix: 예약 날짜 형식 에러 수정
  src/main/resources/static/js/appointment.js
Labels: 🚨 버그

#389 [ALL] Feat: 응애 서비스 이용하지 않는 병원 지도 정보 띄우기
  src/main/java/com/playdata/eungae/admin/service/AdminService.java
  src/main/java/com/playdata/eungae/hospital/controller/HospitalApiController.java
  src/main/java/com/playdata/eungae/hospital/domain/Hospital.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalSearchResponseDto.java
  src/main/java/com/playdata/eungae/initDB.java
  src/main/resources/static/js/map.js
Labels: 💻 백엔드, 🎨 프론트엔드

#392 [FE] Fix: 병원 키워드검색시 오류 수정
  src/main/resources/static/js/map.js
Labels: 🚨 버그, 🎨 프론트엔드

#394 [FE] Fix: 지도 자바스크립트 오류 수정 및 검색 결과 없을 때 처리
  src/main/resources/static/js/map.js
Labels: 🚨 버그

#397 [FE] Fix: 병원 상세 수정
  src/main/resources/static/css/hospital-details.css
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 🎨 프론트엔드

#398 [BE] Feat : 예약 성공시 문자 메세지 전송
  build.gradle
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/config/MessageConfig.java
Labels: 💻 백엔드

#400 [BE] Fix: 별점 계산 수정
  src/main/java/com/playdata/eungae/hospital/dto/HospitalSearchResponseDto.java
Labels: 💻 백엔드, 🚨 버그

#401 [BE] Feat: 병원정보 레디스 캐싱
  src/main/java/com/playdata/eungae/EungaeApplication.java
  src/main/java/com/playdata/eungae/admin/RedisScheduler.java
  src/main/java/com/playdata/eungae/admin/controller/AdminController.java
  src/main/java/com/playdata/eungae/admin/service/AdminService.java
  src/main/java/com/playdata/eungae/initRedis.java
Labels: 💻 백엔드

#405 [ALL] Feat: 코드 리팩토링 및 포맷팅
  src/main/java/com/playdata/eungae/EungaeApplication.java
  src/main/java/com/playdata/eungae/HomeController.java
  src/main/java/com/playdata/eungae/admin/RedisScheduler.java
  src/main/java/com/playdata/eungae/admin/service/AdminService.java
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentApiController.java
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/java/com/playdata/eungae/appointment/domain/Appointment.java
  src/main/java/com/playdata/eungae/appointment/dto/AppointmentRequestDto.java
  src/main/java/com/playdata/eungae/appointment/dto/AppointmentTimeResponseDto.java
  src/main/java/com/playdata/eungae/appointment/dto/ResponsePaymentDto.java
  src/main/java/com/playdata/eungae/appointment/repository/AppointmentRepository.java
  src/main/java/com/playdata/eungae/appointment/service/AppointmentService.java
  src/main/java/com/playdata/eungae/article/dto/CommunityBoardDto.java
  src/main/java/com/playdata/eungae/article/service/NoticeService.java
  src/main/java/com/playdata/eungae/config/MessageConfig.java
  src/main/java/com/playdata/eungae/config/SpringConfig.java
  src/main/java/com/playdata/eungae/doctor/controller/DoctorViewController.java
  src/main/java/com/playdata/eungae/doctor/domain/Doctor.java
  src/main/java/com/playdata/eungae/doctor/dto/DoctorRegisterRequestDto.java
  src/main/java/com/playdata/eungae/doctor/dto/DoctorResponseDto.java
  src/main/java/com/playdata/eungae/exception/GlobalExceptionHandler.java
  src/main/java/com/playdata/eungae/file/ResultFileStore.java
  src/main/java/com/playdata/eungae/hospital/controller/HospitalViewController.java
  src/main/java/com/playdata/eungae/hospital/domain/Hospital.java
  src/main/java/com/playdata/eungae/hospital/domain/HospitalImage.java
  src/main/java/com/playdata/eungae/hospital/dto/HospitalImageResponseDto.java
  src/main/java/com/playdata/eungae/hospital/repository/HospitalScheduleRepository.java
  src/main/java/com/playdata/eungae/hospital/service/HospitalService.java
  src/main/java/com/playdata/eungae/member/controller/MemberApiController.java
  src/main/java/com/playdata/eungae/member/controller/MemberViewController.java
  src/main/java/com/playdata/eungae/member/domain/FavoritesHospital.java
  src/main/java/com/playdata/eungae/member/dto/ChildrenDto.java
  src/main/java/com/playdata/eungae/member/repository/ChildrenRepository.java
  src/main/java/com/playdata/eungae/member/service/ChildrenService.java
  src/main/java/com/playdata/eungae/member/service/MemberService.java
  src/main/java/com/playdata/eungae/review/controller/ReviewApiController.java
  src/main/java/com/playdata/eungae/review/controller/ReviewViewController.java
  src/main/java/com/playdata/eungae/review/service/ReviewService.java
  src/main/java/com/playdata/eungae/security/MemberOAuthUserService.java
  src/main/resources/application.yml
  src/main/resources/static/css/medical-records-details.css
  src/main/resources/templates/contents/member/medical-records-details.html
Labels: 💻 백엔드, 🛠️ 리팩토링

#407 [FE] Feat: 전화번호 복사 기능 구현
  src/main/resources/static/js/hospital-details.js
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 🎨 프론트엔드

#409 [ALL] Fix : appointment payment 취소시 실패 화면으로 redirect 되도록 수정
  src/main/java/com/playdata/eungae/appointment/controller/AppointmentViewController.java
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 💻 백엔드, 🎨 프론트엔드

#408 [ALL] Fix : hospital schedule 휴무일 적용 안되는 오류 수정
  src/main/resources/templates/contents/hospital/hospital-details.html
Labels: 🎨 프론트엔드
